# File location: .github/workflows/docker-build.yml

name: Docker Build and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Workflow
jobs:
  # job called build
  build:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: triwjy/python-helloworld:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
